minimum_reviewers: 2
docker: true
docker_image: ubuntu
build_steps:
 - "env"
 - "echo $SHELL"
 - "make"
 - "make test"
 - "make error"
 - "whoami"
 - "ls /proc/*"
merge: true
org_mode: false
timeout: 2916
env:
 TEST_ENVIRONMENT: mytestvalue
