minimum_reviewers: 2
docker: true
docker_image: "davidxd/yoko"
build_steps:
 - "env"
 - "echo $SHELL"
 - "make"
 - "make test"
 - "make error"
 - "which escript"
 - "echo $APP_VERSION"
 - "echo $DIALYZER_PLT"
 - "whoami"
 - "ls /proc/*"
merge: true
org_mode: false
timeout: 2916
env:
 TEST_ENVIRONMENT: mytestvalue
 APP_VERSION: 23
