minimum_reviewers: 2
docker: true
docker_image: ubuntu
build_steps:
 - "uptime"
 - "env"
 - "echo $SHELL"
 - "whoami"
 - "ls /proc/*"
merge: true
org_mode: false
timeout: 2915
env:
 TEST_ENVIRONMENT: mytestvalue
